### ISSUE TITLE
TemplateHaskellQuotes broken

### ISSUE THREAD

**Issue by alexkazik** [haskell/stylish-haskell#141]
I have a few files with TemplateHaskellQuotes enabled (as a pragma in the file).
stylish-haskell reports: `Language.Haskell.Stylish.Parse.parseModule: could not parse ./src/Compiler/Function/Generate.hs: ParseFailed (SrcLoc "<unknown>.hs" 83 47) "Improper character constant or misplaced '"`
At that position is a `'return`.
When I enable TemplateHaskell in stylish-haskell's config file (not changing the source) it get's parsed correctly.
stylish-haskell 0.6.1.0

**Comment by neongreen** [comment]
Can reproduce with 0.7.1.0. I think this is a haskell-src-exts bug.

**Comment by neongreen** [comment]
https://github.com/haskell-suite/haskell-src-exts/issues/357

**Comment by EncodePanda** [comment]
stylish-haskell no longer depends on haskell-src-exts
