### ISSUE TITLE
Installation uses some deprecated compilation options

### ISSUE THREAD

**Issue by hseg** [haskell/stylish-haskell#33]
Too many to note now, but many dependencies use -fglasgow-exts,
haskell-src-exts uses an old interface of runTests,
resourcet shadows the binding Control.Monad.Reader.Class.reader,
etc. etc.
The full list can be found by running cabal update && cabal install stylish-haskell
Unfortunately, I didn't have the foresight to pipe the output of cabal install to a file,
and can't undo the installation. Hopefully, this description is detailled enough.
Please forward upstream.

**Comment by andreasabel** [comment]
I suggest to close this stale issue.
