### ISSUE TITLE
Install fails due to Variable not in scope: (<>)

### ISSUE THREAD

**Issue by poneill** [haskell/stylish-haskell#333]
I'm trying to install stylish-haskell using

`cabal install stylish-haskell`

which results in the long error message, the gist of which is:

```lib/Language/Haskell/Stylish/Config/Cabal.hs:91:45: error:
    • Variable not in scope: (<>) :: IO () -> String -> IO a1
    • Perhaps you meant one of these:
        ‘<*>’ (imported from Prelude), ‘*>’ (imported from Prelude),
        ‘>>’ (imported from Prelude)
cabal: Leaving directory '/tmp/cabal-tmp-1019853/stylish-haskell-0.9.4.4'
cabal: Error: some packages failed to install:
stylish-haskell-0.9.4.4 failed during the building phase. The exception was:
ExitFailure 1
```

it seems that ghc is expecting (<>) to be present in the prelude and not finding it [?]

System specs:
  - The Glorious Glasgow Haskell Compilation System, version 8.0.2
  - cabal-install version 1.24.0.2
  - base==4.9.1.0

I'm not sure if this is actually a stylish-haskell bug rather than a cabal bug, but in any case thanks in advance.

**Comment by andreasabel** [comment]
@poneill wrote:
> * The Glorious Glasgow Haskell Compilation System, version 8.0.2

This GHC was already ancient at the time you filed the issue (at least GHC 9.0.1 was already out then).

In the meantime, this issue has been fixed by a [Hackage revision](https://hackage.haskell.org/package/stylish-haskell-0.9.4.4/revisions/), so, should be closed.
