### ISSUE TITLE
script/latest.sh doesn't work anymore.

### ISSUE THREAD

**Issue by turboMaCk** [haskell/stylish-haskell#366]
The quick install script located in scripts directory of this repository seems to be broken.

```
curl -sSL https://raw.github.com/jaspervdj/stylish-haskell/master/scripts/latest.sh | sh -s $(find . -type f -name "*.hs" ! -path "*.stack-work*") -i
Downloading and running stylish-haskell...
#=#=#                                                                         

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

It seems that the url for tarball might not be correctly parsed out of HTML or something like that.

**Comment by EncodePanda** [comment]
We've recently migrated to haskell organization but scripts were not updated. There is a PR to fix that https://github.com/haskell/stylish-haskell/pull/364
I'm waiting for @nicuveo to rebase it so I can merge it :)

**Comment by turboMaCk** [comment]
Thanks Pawel.

I've fixed this problem in our CI using this custom shell script which pins stylish to exact version for now:

```
#! /usr/bin/env bash

set -e

PACKAGE=stylish-haskell
VERSION=v0.12.2.0
echo Downloading and running $PACKAGE...

URL=https://github.com/haskell/$PACKAGE/releases/download/$VERSION/$PACKAGE-$VERSION-linux-x86_64.tar.gz
TEMP=$(mktemp --directory .$PACKAGE-XXXXX)

cleanup() {
    rm -r $TEMP
}
trap cleanup EXIT

curl --progress-bar --location -o$TEMP/$PACKAGE.tar.gz $URL
tar -xzf $TEMP/$PACKAGE.tar.gz -C$TEMP
$TEMP/$PACKAGE-$VERSION-linux-x86_64/$PACKAGE $*
```

**Comment by EncodePanda** [comment]
https://github.com/haskell/stylish-haskell/pull/364 this just got in
@turboMaCk if you could please confirm it works now for you

**Comment by turboMaCk** [comment]
I can confirm this works again.
