### ISSUE TITLE
optparse-applicative dependency

### ISSUE THREAD

**Issue by StevenXL** [haskell/stylish-haskell#377]
Hi folks,

The latest version of [stylish-haskell](https://hackage.haskell.org/package/stylish-haskell-0.12.2.0/candidate) on Hackage depends on `optparse-applicative (>=0.12 && <0.16)`.

This has led to a situation where our team is using `optparse-applicative v0.15` in our own projects. 

Is there a push to move towards a more recent version of `optparse-applicative`?

**Comment by wldhx** [comment]
Resolved in 0.14.0.1.
