### ISSUE TITLE
Add support for aeson >= 2.0

### ISSUE THREAD

**Issue by jneira** [haskell/stylish-haskell#387]
* As it is needed for build the package alongside other packages using that version of aeson (like haskell-language-server, see https://github.com/haskell/haskell-language-server/issues/2477)
* And include the security fix of course
* See https://github.com/haskell/aeson/issues/881
* If possible it would be great to support also aeson < 2.0

**Comment by jaspervdj** [comment]
Fixed in `v0.14.0.0`
