### ISSUE TITLE
parse error on input on "type (*)"

### ISSUE THREAD

**Issue by Mikolaj** [haskell/stylish-haskell#414]
Stylish-haskell works great with type-level (*) taken from

```
import GHC.TypeLits
```

but it chokes at

```
import GHC.TypeLits (type (*))
```

with

```
Warning (stylish-haskell): stylish-haskell failed: <string>:16:48: error:
    parse error on input `*'
```

**Comment by Lev135** [comment]
Is it still an issue? I tried to reproduce it with `stylish-haskell 0.14.3.0` and `ghc-9.2.4`: with `TypeOperators` and `NoStarIsType` stylish works fine, without `NoStarIsType` both ghci and stylish produce the same parse error. Maybe this was a problem only before `NoStarIsType` was fixed? Or I'm just looking on incorrect combination of settings

**Comment by Mikolaj** [comment]
I just tried to verify by compiling stylish-haskell-0.14.3.0 with ghcup-installed ghc-9.2.5 and got the following:

```
[ 4 of 26] Compiling Language.Haskell.Stylish.GHC ( lib/Language/Haskell/Stylish/GHC.hs, dist/build/Language/Haskell/Stylish/GHC.o, dist/build/Language/Haskell/Stylish/GHC.dyn_o )

lib/Language/Haskell/Stylish/GHC.hs:71:32: error:
    • Couldn't match expected type ‘GHC.Settings’
                  with actual type ‘ghc-lib-parser-9.2.5.20221107:GHC.Settings.Settings’
      NB: ‘GHC.Settings’
            is defined in ‘GHC.Settings’ in package ‘ghc-9.2.5’
          ‘ghc-lib-parser-9.2.5.20221107:GHC.Settings.Settings’
            is defined in ‘GHC.Settings’
                in package ‘ghc-lib-parser-9.2.5.20221107’
    • In the first argument of ‘defaultDynFlags’, namely
        ‘GHCEx.fakeSettings’
      In the expression:
        defaultDynFlags GHCEx.fakeSettings GHCEx.fakeLlvmConfig
      In an equation for ‘baseDynFlags’:
          baseDynFlags
            = defaultDynFlags GHCEx.fakeSettings GHCEx.fakeLlvmConfig
   |
71 | baseDynFlags = defaultDynFlags GHCEx.fakeSettings GHCEx.fakeLlvmConfig
   |                                ^^^^^^^^^^^^^^^^^^

lib/Language/Haskell/Stylish/GHC.hs:71:51: error:
    • Couldn't match expected type ‘GHC.LlvmConfig’
                  with actual type ‘ghc-lib-parser-9.2.5.20221107:GHC.Driver.Session.LlvmConfig’
      NB: ‘GHC.LlvmConfig’
            is defined in ‘GHC.Driver.Session’ in package ‘ghc-9.2.5’
          ‘ghc-lib-parser-9.2.5.20221107:GHC.Driver.Session.LlvmConfig’
            is defined in ‘GHC.Driver.Session’
                in package ‘ghc-lib-parser-9.2.5.20221107’
    • In the second argument of ‘defaultDynFlags’, namely
        ‘GHCEx.fakeLlvmConfig’
      In the expression:
        defaultDynFlags GHCEx.fakeSettings GHCEx.fakeLlvmConfig
      In an equation for ‘baseDynFlags’:
          baseDynFlags
            = defaultDynFlags GHCEx.fakeSettings GHCEx.fakeLlvmConfig
   |
71 | baseDynFlags = defaultDynFlags GHCEx.fakeSettings GHCEx.fakeLlvmConfig
   |                                                   ^^^^^^^^^^^^^^^^^^^^
Error: cabal: Failed to build stylish-haskell-0.14.3.0 (which is required by
exe:stylish-haskell from stylish-haskell-0.14.3.0). See the build log above
for details.
```

Shall I just revert to ghc-9.2.4 or is there any commandline option that helps?

**Comment by Lev135** [comment]
The errors looks very similar to the problems with [9.2.3](https://github.com/haskell/stylish-haskell/issues/405#issue-1266641217). And as it's [said below](https://github.com/haskell/stylish-haskell/issues/405#issuecomment-1366208101) it also fails with 9.2.5. Previously, I had to use +ghc-lib, but with 9.2.4 everything works without extra flags. Anyway, its another issue and I hope adding a flag will help

**Comment by Mikolaj** [comment]
Hah, yes, I've actually reported it for 9.2.3, The same workaround works for 9.2.5:

    cabal install --constraint "stylish-haskell +ghc-lib" stylish-haskell

The main issue persists. If I add both TypeOperators and NoStarIsType to the file's header or to `language_extensions` in `.stylish-haskell.yaml`, it works fine. But apparently it can't read it from my cabal file. Here is a repro branch: 

https://github.com/Mikolaj/horde-ad/tree/stylish-haskell/issues/414

**Comment by Lev135** [comment]
It seems that I've found the root of the problem: its a problem with NoXyz extensions for cabal file. If its so, this should be closed by the PR above. I hope this is the case

**Comment by Lev135** [comment]
The PR was merged into the main, so it would be nice if you could check if everything works fine now. No hurry, of course, just to close this issue  as completed someday in the future

**Comment by Mikolaj** [comment]
Thank you very much. I'm not using this feature (`*` on the type level) right now (hence the dedicated branch for repro), but I will mostly probably start using it again in the future and then I will know for sure if it works. Let me close now and I will reopen in the unlikely case that I spot errors once I use this functionality daily again.
